add homework #12
nikitaekaterinin/java-course-homework pull request #18
Opened 2024-05-14 19:15 UTC by nikitaekaterinin

Added homework #12

2024-05-14 19:29 UTC, alexshamrai requested changes

2024-05-14 19:29 UTC, alexshamrai commented on src/main/java/org/example/homework12/Main.java
> +                .max()
`max` can accept Compataror and you can simplify the logic to one stream. please think how you can improve it

2024-05-15 07:13 UTC, nikitaekaterinin commented on src/main/java/org/example/homework12/Main.java
> +                .max()
fix added

2024-05-15 07:28 UTC, alexshamrai approved these changes

2024-05-16 10:41 UTC, merged